Repository yosefalnajjarofficial/handyman, pull requests merged in 2019-10, with the labels that each got.

#23 fixed routes and reduced them
  client/public/index.html
  client/src/components/App/index.js
  client/src/components/Pages/Hire/index.js
  client/src/components/Pages/Signup/index.js
  client/src/components/Pages/login/index.js
  client/src/components/common/Layout/index.js
  package-lock.json
  package.json
  server/app.js
Labels: High Priority, for merge

#26 add descriptive topics in the landing page
  client/src/components/Pages/Home/index.js
Labels: for merge

#27 Loading
  client/package-lock.json
  client/src/components/App/index.js
  client/src/components/Pages/JobsPage/index.js
  client/src/components/Pages/OneServices/index.js
  client/src/components/Pages/Profile/index.js
  client/src/components/Pages/Services/index.js
  client/src/components/common/Loader/index.css
  client/src/components/common/Loader/index.js
Labels: for merge

#24 15 auth
  client/src/components/App/index.js
  client/src/components/Pages/Signup/index.js
  server/controllers/index.js
  server/controllers/routes/signup.js
Labels: for merge

#28 Images For Services
  client/src/components/Pages/Services/index.js
  client/src/components/common/serviceCard/index.js
  client/src/components/common/serviceCard/style.css
  client/src/components/utils/servicesPics.js
Labels: for merge

#33 refactor the Back Button
  client/src/components/App/index.js
  client/src/components/Pages/Signup/index.js
  client/src/components/common/Header/index.js
  client/src/components/common/Layout/index.js
Labels: for merge

#30 Slider Menu
  client/src/components/App/index.js
  client/src/components/Pages/Logout/index.js
  client/src/components/Pages/index.js
  client/src/components/common/HandymanCard/style.css
  client/src/components/common/Header/index.js
  client/src/components/common/Layout/index.js
  client/src/components/common/SideDrawer/index.js
  client/src/components/utils/logout.js
Labels: for merge

#35 Notification
  client/src/components/App/style.css
  client/src/components/Pages/OneServices/index.js
  client/src/components/Pages/OneServices/style.css
Labels: for merge

#36 handling errors in the front end
  client/src/components/Pages/Signup/index.js
  client/src/components/Pages/Signup/style.css
Labels: awaiting review

#31 got the tests out of server file
  package.json
  server/tests/index.js
  server/tests/queries/index.js
  server/tests/routes/index.js
  server/tests/utils/index.js
  tests/index.js
  tests/queries/getJob.test.js
  tests/queries/getOneservice.test.js
  tests/queries/getProfile.test.js
  tests/queries/getServices.test.js
  tests/queries/getUserByEmail.test.js
  tests/queries/index.test.js
  tests/queries/postJob.test.js
  tests/queries/signupQuery.test.js
  tests/routes/getJob.test.js
  tests/routes/getOneService.test.js
  tests/routes/getProfile.test.js
  tests/routes/getServices.test.js
  tests/routes/index.test.js
  tests/routes/login.test.js
  tests/routes/postJob.test.js
  tests/routes/signup.test.js
Labels: for merge

#34 16 fix console err
  client/src/components/App/index.js
  client/src/components/Pages/Hire/index.js
  client/src/components/Pages/Home/index.js
  client/src/components/Pages/JobsPage/index.js
  client/src/components/Pages/OneServices/index.js
  client/src/components/Pages/Profile/index.js
  client/src/components/Pages/Services/index.js
  client/src/components/Pages/login/index.js
  client/src/components/common/Button/index.js
  client/src/components/common/HandymanCard/index.js
  client/src/components/common/Header/index.js
  client/src/components/common/Header/style.css
  client/src/components/common/JobCard/index.js
  client/src/components/common/LabeledInput/index.js
  client/src/components/common/Layout/index.js
  client/src/components/common/SearchInput/index.js
  client/src/components/common/SideDrawer/index.js
  client/src/components/common/sliderCard/index.js
  server/app.js
Labels: for merge

#37 edited the db and corrected everything accordingly
  client/src/components/Pages/JobsPage/index.js
  server/app.js
  server/db/config/build.sql
  server/db/config/createdb.sql
  server/db/config/fakeData.sql
  server/db/queries/addHandyman.js
  server/db/queries/getJobs.js
  server/db/queries/getOneService.js
  server/db/queries/getProfile.js
  server/db/queries/postJob.js
Labels: awaiting review

#40 Readme
  README.md
  server/app.js
Labels: for merge
